:queues:
  - default
  - mailers
  - billing
:schedule:
  perform_subscriptions:
    every: "1m"
    class: PerformSubscriptionsJob
  close_time_tracking:
    every: "1m"
    class: FinishTimeTrackingJob
